CC = gcc
CFLAGS = -Wall -g
TARGETS = server client

all: clean $(TARGETS)

server: server.c
	@$(CC) $(CFLAGS) -o server server.c

client: client.c
	@$(CC) $(CFLAGS) -o client client.c

clean:
	@rm -f $(TARGETS)
